server:
  port: 8080
spring:
  profiles:
    active: sharding
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xialuo.shardingjdbcreadorwrite.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
